CUDA_VISIBLE_DEVICES=0 python3 -u train.py \
    --train_data_path ./data/ARSC/ARSC_train.json \
    --val_data_path ./data/ARSC/ \
    --test_data_path ./data/ARSC/ \
    -N 2 \
    -K 5 \
    -Q 5 \
    --train_episodes 30000 \
    --val_steps 500 \
    --max_length 512 \
    --hidden_size 128 \
    --att_dim 64 \
    --induction_iters 3 \
    --relation_size 100 \
    -B 32 \
    --lr 1e-4 \
    --use_cuda \
    --emb_path ./embedding/glove.6B.300d/ \
    --logdir ./log > ./log/run.log 2>&1 &